### ISSUE TITLE
Encontrei um problema, por favor consertar

### ISSUE THREAD

**Issue by filipedeschamps** [otaviopace/cep-callback#7]
Encontrei um problema ao usar o cep-callback, ele usa callback.

Boa noite.

**Comment by dann95** [comment]
@ DCMA , ping!...

**Comment by evaporei** [comment]
Senhor Filipe. Caso esteja com problemas com callbacks, pode utilizar uma versão semelhante do projeto, mas um pouco piorada. Ta aqui o [link dela](https://github.com/filipedeschamps/cep-promise).

Boa noite, espero que encontre seu CEP. :slightly_smiling_face:

**Comment by filipedeschamps** [comment]
Senhor Otávio Pace, primeiramente boa noite.

Não conhecia este software apontado no hyperlink acima.

Obrigado pela indicação.

Obrigado e bom dia.

**Comment by dann95** [comment]
@filipedeschamps essa lib já fez história em? hahaha, usei ela pra ensinar Promises e Browserify (quando usavam browserify) pros estagiários da empresa, e parece que segue rendendo algumas piadas ^.-

**Comment by filipedeschamps** [comment]
@dann95 sério? Puts que massa!!!!!! Olha isso @lucianopf

**Comment by lucianopf** [comment]
Que massa @dann95 !!!

Um dia vamos poder usar como exemplo de machine learning e computação quântica! 😂 🤞

**Comment by dann95** [comment]
@filipedeschamps yeah, foi prático, e rendeu, acho que o mlk aprendeu :p

**Comment by dann95** [comment]
@lucianopf eu acho que daqui a pouco o uso dela vai ser alimentar uma base descentralizada de ceps, pq dos correios é paga...

**Comment by dann95** [comment]
@lucianopf mas ql seria o machine learning com ceps? curioso com a proposta..

**Comment by lucianopf** [comment]
Era piada, só usando buzzwords mesmo! 😂

**Comment by dann95** [comment]
@lucianopf i know, mas tem q achar um sentido, já vi análise de dados pra cada coisa que não vou desmerecer a piada...

**Comment by evaporei** [comment]
Já que a lib se encaixa perfeitamente com o modelo node de se lidar com asincronía, essa issue está sendo fechada :slightly_smiling_face:
